### ISSUE TITLE
Fresh "install" on CentOS 7, 2 containers with exitcode 1

### ISSUE THREAD

**Issue by tkorves** [shopwareLabs/shopware-docker#5]
Hi there,

I tried using your Docker-Stack on a freshly installed CentOS 7 with PHP7 and SELinux disabled. I've got two containers which aren't able to start (exited (1)). Here is a snippet from my SSH consoles output - any help is appreciated:

[root@dev-shopwaredckr01 shopware-docker]# docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                      PORTS               NAMES
29f395e7c8b3        shopwaredocker_app_server   "docker-php-entrypoin"   39 seconds ago      Exited (1) 24 seconds ago                       shopwaredocker_app_server_1
33a6328aa1fa        shopwaredocker_app_redis    "docker-entrypoint.sh"   40 seconds ago      Up 38 seconds               6379/tcp            shopwaredocker_app_redis_1
9f691f182ac7        shopwaredocker_app_es       "/bin/bash bin/es-doc"   40 seconds ago      Exited (1) 23 seconds ago                       shopwaredocker_app_es_1
7a1d1cd8b7c6        shopwaredocker_app_mysql    "docker-entrypoint.sh"   40 seconds ago      Up 39 seconds               3306/tcp            shopwaredocker_app_mysql_1
[root@dev-shopwaredckr01 shopware-docker]# docker logs shopwaredocker_app_server_1
chown: invalid user: 'app-shell:app-shell'
Agent pid 9
Identity added: /home/app-shell/.ssh/id_rsa (rsa w/o comment)
AH00543: apache2: bad user name app-shell
[root@dev-shopwaredckr01 shopware-docker]# docker logs shopwaredocker_app_es_1
[2018-03-15T18:27:06,938][INFO ][o.e.n.Node               ] [] initializing ...
[2018-03-15T18:27:06,978][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:267) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_141]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_141]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_141]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:264) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more

Thanks for any advice.

BR, Tim

**Comment by tkorves** [comment]
Docker version 1.12.6, build 3e8e77d/1.12.6

PHP 7.0.28 (cli) (built: Mar  1 2018 10:03:25) ( NTS )

**Comment by teiling88** [comment]
can you post the log of ```./psh.phar docker:start```?

**Comment by tkorves** [comment]
[root@dev-shopwaredckr01 shopware-docker]# ./psh.phar docker:start

###################
Starting Execution of 'docker:start' ('dev-ops/docker/actions/start.sh')


(1/6) Starting
> echo "COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}"
        COMPOSE_PROJECT_NAME:

(2/6) Starting
> dev-ops/docker/containers/scriptcreator.sh
        Created /opt/shopware-docker/dev-ops/docker/containers/php7/createuser.sh
        Created /opt/shopware-docker/dev-ops/docker/containers/mysql/createuser.sh

(3/6) Starting
> docker-compose build && docker-compose up -d
        Building app_mysql
        Step 1 : FROM mysql:5.7
         ---> 5195076672a7
        Step 2 : RUN apt-get update   && apt-get install --no-install-recommends -y      vim      netcat-openbsd
         ---> Using cache
         ---> 2cd731a7f8b0
        Step 3 : ADD dev.cnf /etc/mysql/conf.d/dev.cnf
         ---> Using cache
         ---> 158d021a505b
        Step 4 : ADD remote-access.cnf /etc/mysql/conf.d/remote-access.cnf
         ---> Using cache
         ---> 7ecd11e36940
        Step 5 : ADD performance-schema.cnf /etc/mysql/conf.d/performance-schema.cnf
         ---> Using cache
         ---> 2246a5d0f8a0
        Step 6 : COPY createuser.sh /tmp/createuser.sh
         ---> Using cache
         ---> 3db524b95df5
        Step 7 : RUN chmod +rwx /tmp/createuser.sh
         ---> Using cache
         ---> 81bbf09893b8
        Step 8 : RUN /tmp/createuser.sh
         ---> Using cache
         ---> 3f5829eb5ffd
        Step 9 : COPY grant.sql /docker-entrypoint-initdb.d/grant.sql
         ---> Using cache
         ---> 5e337514b266
        Successfully built 5e337514b266
        Building app_redis
        Step 1 : FROM redis:4
         ---> 4760dc956b2d
        Successfully built 4760dc956b2d
        Building app_es
        Step 1 : FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.2
         ---> ca27036dd5e7
        Successfully built ca27036dd5e7
        Building app_server
        Step 1 : FROM php:7.1-apache
         ---> 437508e0f491
        Step 2 : RUN apt-get update -qq && apt-get install -y -qq         libicu-dev         libfreetype6-dev         libjpeg62-turbo-dev         libmcrypt-dev         libpng12-dev         libcurl4-openssl-dev         software-properties-common          libcurl3 curl         git         zip         unzip         openjdk-7-jdk         inotify-tools
         ---> Using cache
         ---> ce0b9191214a
        Step 3 : RUN apt-get update -qq && apt-get install -y -qq         build-essential         libxml2-dev libxslt1-dev zlib1g-dev         git         mysql-client         sshpass         nano         sudo         vim         graphviz         netcat-openbsd         nodejs npm nodejs-legacy         ant
         ---> Using cache
         ---> f1ed7b42c4b3
        Step 4 : RUN docker-php-ext-install iconv mcrypt mbstring     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && docker-php-ext-install zip     && docker-php-ext-install curl     && docker-php-ext-install intl     && docker-php-ext-install pdo     && docker-php-ext-install pdo_mysql
         ---> Using cache
         ---> 9862d1faf0b3
        Step 5 : RUN pecl install xdebug     && docker-php-ext-enable xdebug
         ---> Using cache
         ---> db122b1d4676
        Step 6 : RUN pecl install redis     && docker-php-ext-enable redis
         ---> Using cache
         ---> b11d060284a0
        Step 7 : RUN npm install -g grunt-cli bower grunt jasmine
         ---> Using cache
         ---> d2963d700b1a
        Step 8 : ADD server-apache2-vhosts.conf /etc/apache2/sites-enabled/000-default.conf
         ---> Using cache
         ---> 0f2f79f10f47
        Step 9 : ADD server-apache2-run-as.conf /etc/apache2/conf-available
         ---> Using cache
         ---> 428d63102fac
        Step 10 : RUN ln -s /etc/apache2/conf-available/server-apache2-run-as.conf /etc/apache2/conf-enabled
         ---> Using cache
         ---> ac559dea7ba6
        Step 11 : ADD php-config.ini /usr/local/etc/php/conf.d/php-config.ini
         ---> Using cache
         ---> 389c50bb135f
        Step 12 : ADD timezone-berlin.ini /usr/local/etc/php/conf.d/timezone.ini
         ---> Using cache
         ---> 35b4f5a9b74f
        Step 13 : ADD xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
         ---> Using cache
         ---> b59abd2f3bbd
        Step 14 : RUN a2enmod rewrite
         ---> Using cache
         ---> 0b990098fd5c
        Step 15 : COPY createuser.sh /tmp/createuser.sh
         ---> Using cache
         ---> 8959045f2590
        Step 16 : RUN chmod +rwx /tmp/createuser.sh
         ---> Using cache
         ---> c019b993c9a5
        Step 17 : RUN /tmp/createuser.sh
         ---> Using cache
         ---> 630c6c1c7fee
        Step 18 : RUN echo "alias ll='ls -ahl'" >> /etc/bash.bashrc
         ---> Using cache
         ---> cd1692134487
        Step 19 : WORKDIR /var/www/shopware
         ---> Using cache
         ---> 50ac70f79212
        Step 20 : COPY wait.sh /tmp/wait.sh
         ---> Using cache
         ---> a76f84ccfc07
        Step 21 : RUN chmod +x /tmp/wait.sh
         ---> Using cache
         ---> 39d84bee989f
        Step 22 : COPY id_rsa /home/app-shell/.ssh
         ---> Using cache
         ---> c122efb4f85a
        Step 23 : COPY id_rsa.pub /home/app-shell/.ssh
         ---> Using cache
         ---> 88d78bee8fef
        Step 24 : COPY run-container.sh /run-container.sh
         ---> Using cache
         ---> de327eb1bf25
        Step 25 : RUN chmod +x /run-container.sh
         ---> Using cache
         ---> e03a334a60fd
        Step 26 : RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
         ---> Using cache
         ---> 19ce3524c688
        Step 27 : RUN php composer-setup.php --install-dir=/usr/local/bin/ --filename=composer
         ---> Using cache
         ---> 912f0ea58e7a
        Step 28 : RUN php -r "unlink('composer-setup.php');"
         ---> Using cache
         ---> 2534be23a70b
        Step 29 : CMD /run-container.sh
         ---> Using cache
         ---> 875aae1d1aed
        Successfully built 875aae1d1aed
        shopwaredocker_app_mysql_1 is up-to-date
        Starting shopwaredocker_app_es_1 ...
        shopwaredocker_app_redis_1 is up-to-date
Starting shopwaredocker_app_server_1 ... done

(4/6) Starting
> wait

(5/6) Starting
> echo "All containers started successfully"
        All containers started successfully

(6/6) Starting
> echo "Web server IP: http://10.100.111.46"
        Web server IP: http://10.100.111.46

Duration: 2s
All commands successfully executed!

**Comment by tkorves** [comment]
Shopware-App-Server:
chown: invalid user: 'app-shell:app-shell'
Agent pid 9
Identity added: /home/app-shell/.ssh/id_rsa (rsa w/o comment)
AH00543: apache2: bad user name app-shell
chown: invalid user: 'app-shell:app-shell'
Identity added: /home/app-shell/.ssh/id_rsa (rsa w/o comment)
Agent pid 9
AH00543: apache2: bad user name app-shell

Shopware-App-ES:
[2018-03-15T18:27:06,938][INFO ][o.e.n.Node               ] [] initializing ...
[2018-03-15T18:27:06,978][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:267) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_141]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_141]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_141]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:264) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more
[2018-03-16T12:13:42,330][INFO ][o.e.n.Node               ] [] initializing ...
[2018-03-16T12:13:42,356][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:127) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.5.2.jar:5.5.2]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:267) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_141]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_141]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_141]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:264) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.node.Node.<init>(Node.java:244) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:232) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) ~[elasticsearch-5.5.2.jar:5.5.2]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) ~[elasticsearch-5.5.2.jar:5.5.2]
        ... 6 more

**Comment by teiling88** [comment]
I think he is not able to create the User `app-shell`. I'm not a CentOs expert but the creating process is done here https://github.com/shopwareLabs/shopware-docker/blob/master/dev-ops/docker/containers/scriptcreator.sh.

**Comment by tkorves** [comment]
Hi @teiling88,
thanks for this hint - this worked out at least for the app-server. The Elastic Search component still throws an exception caused by an AccessDeniedException for /usr/share/elasticsearch/data/nodes ... Need to dig deeper there.

**Comment by teiling88** [comment]
Hmm maybe is this helpfull: https://github.com/shopwareLabs/shopware-docker#troubleshooting

**Comment by tkorves** [comment]
Yep, was helpful - both ... Thanks a lot ... Need some manual re-work to be run on CentOS, but if it runs, it's all good. 👍
