### ISSUE TITLE
Slim Application Error: file_put_contents failed to open stream: Permission denied

### ISSUE THREAD

**Issue by nikolayk812** [shopwareLabs/shopware-docker#50]
I get this error when hitting localhost:8083 after I was able to start up the environment.

```
Slim Application Error
The application could not run because of the following error:

Details
Type: ErrorException
Code: 2
Message: file_put_contents(/var/www/shopware/shopware/recovery/install/data/uniqueid.txt): failed to open stream: Permission denied
File: /var/www/shopware/shopware/recovery/common/src/Service/UniqueIdGenerator.php
Line: 83
Trace
#0 [internal function]: Slim\Slim::handleErrors(2, 'file_put_conten...', '/var/www/shopwa...', 83, Array)
#1 /var/www/shopware/shopware/recovery/common/src/Service/UniqueIdGenerator.php(83): file_put_contents('/var/www/shopwa...', '2J1crQvtyMnug97...')
#2 /var/www/shopware/shopware/recovery/common/src/Service/UniqueIdGenerator.php(56): Shopware\Recovery\Common\Service\UniqueIdGenerator->saveUniqueId('2J1crQvtyMnug97...')
#3 /var/www/shopware/shopware/recovery/install/src/ContainerProvider.php(209): Shopware\Recovery\Common\Service\UniqueIdGenerator->getUniqueId()
#4 /var/www/shopware/shopware/recovery/common/vendor/pimple/pimple/src/Pimple/Container.php(118): Shopware\Recovery\Install\ContainerProvider->Shopware\Recovery\Install\{closure}(Object(Pimple\Container))
#5 /var/www/shopware/shopware/recovery/install/src/app.php(203): Pimple\Container->offsetGet('shopware.notify')
#6 [internal function]: {closure}()
#7 /var/www/shopware/shopware/recovery/common/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#8 /var/www/shopware/shopware/recovery/common/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#9 /var/www/shopware/shopware/recovery/common/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /var/www/shopware/shopware/recovery/common/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /var/www/shopware/shopware/recovery/common/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#12 /var/www/shopware/shopware/recovery/common/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#13 /var/www/shopware/shopware/recovery/install/index.php(75): Slim\Slim->run()
#14 {main}
```

**Comment by nikolayk812** [comment]
By the way this issue was reproduced for me: https://github.com/shopwareLabs/shopware-docker/issues/29, `sudo` solved the case.
